# Generated by Django 2.2.7 on 2019-11-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resposta',
            old_name='estrela',
            new_name='voto',
        ),
    ]
